### ISSUE TITLE
The design of the home page could be jazzier

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#13]
Designs welcome - create a blog post with some images of your designs. Suggestions for colours and fonts welcome!

**Comment by RizBizKits** [comment]
Working on this currently 🌟

**Comment by AnnaDodson** [comment]
Love the designs shown in #36 :heart_eyes:  My only feedback is to make the post titles on the home page not in all capitals, as we learned at Tech Notts, they might be difficult for people to read.

Love the fonts and title banner very very very much :heart:

**Comment by jamietanna** [comment]
Ooh I'm really liking this new design - this looks like an awesome new look, am looking forward to seeing the PR so I can navigate around and see more how it feels.

One question I have is how it'd look with code snippets being embedded, such as in _Docker Who_

**Comment by RizBizKits** [comment]
> Love the designs shown in #36 😍 My only feedback is to make the post titles on the home page not in all capitals, as we learned at Tech Notts, they might be difficult for people to read.
> 
> Love the fonts and title banner very very very much ❤️

Thank you, Anna! And yes, I considered not having all-caps but realized only later that the font doesn't have any lower case characters :( I'll try and find something similar that's got lower cased characters, too...

**Comment by RizBizKits** [comment]
> Ooh I'm really liking this new design - this looks like an awesome new look, am looking forward to seeing the PR so I can navigate around and see more how it feels.
> 
> One question I have is how it'd look with code snippets being embedded, such as in _Docker Who_

Thanks, Jamie. I've tried to follow best practices for adding additional styles (*fingers crossed*) but definitely would appreciate if you help sort out any rookie mistakes I might have committed 🥇 Ohhh, yes, code snippets, good point! I'll keep that in mind ^_^
