### ISSUE TITLE
Add a page that will be used for showing all the contributors

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#16]
A page should be created for all contributors to be listed on. The page should be accessible from the nav, next to the About page on the right.

- Create a page called `contributors.md` in the root of the project
- Make sure the front matter is correct for it to be listed in the header next to About page
- Add an intro to what this page will be for

**Comment by carolgilabert** [comment]
Claiming it! 🙋‍♀️

**Comment by AnnaDodson** [comment]
Closed in #34
