### ISSUE TITLE
Add authors name under the titles on the home page

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#33]
On the home page where all the blog posts are listed, it would be nice to see the authors names too,

Something like this but feel free to add styling:

![image](https://user-images.githubusercontent.com/14791708/46905181-f7811800-cee7-11e8-8b52-f416afe2784a.png)

**Comment by daveNewcastle** [comment]
I'll give this a go.

**Comment by AnnaDodson** [comment]
Closed in #35
