### ISSUE TITLE
There's no Favicon

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#5]
It would be really nice to have a homemade [favicon](https://www.abeautifulsite.net/what-are-favicons) for the site. If you want to make one, please also add a blog post - I'd love to hear about it.

**Comment by BabyMaybe** [comment]
Hi! I would be interested in doing this! Was there a design you had in mind?

**Comment by AnnaDodson** [comment]
Hi! Nope, I'm happy to leave it open! The website is all about communities and creativity, so whatever works for that. Please also add a blog post explaining your design and what open source tools you've used (if any). I'll add a claimed label if you do want to work on this 😊

**Comment by BabyMaybe** [comment]
Yeah! I'll take it!

**Comment by BabyMaybe** [comment]
Just pushed my favicon up! See #21

**Comment by AnnaDodson** [comment]
Closed in #21
