### ISSUE TITLE
Ruby Sass that's used is deprecated - needs replacing

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#51]
When getting the site running locally the below message is shown.

The Sass dependency needs removing and replacing. Suggest looking at the Jekyll docs to see what dependency is suggested to replace it with.

![Screenshot from 2019-10-01 20-39-55](https://user-images.githubusercontent.com/14791708/65994659-ca789d00-e48b-11e9-8d9f-b470b9c61d6b.png)

**Comment by bitshiftsdotio** [comment]
Looking 👀
