### ISSUE TITLE
A new events page for all Hacktoberfest events in and around Nottingham this month

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#55]
**Is this issue a feature request or a bug report?**

- [x] Feature
- [ ] Bug

**What is the expected behaviour/what feature are you proposing?**

There's a few events this month and it would be great to list them all here for people to easily see.

A new page in the nav called Events with the following events listed:

- Homebrew website club (three in October)
- Tech Nottingham workshop
- NottsJS workshop
- DDD East Midlands

**How can the bug be reproduced?**

**Comment by RizBizKits** [comment]
on it! gonna get the events listed and nice 👩‍🎨

**Comment by AnnaDodson** [comment]
Done in !61
