### ISSUE TITLE
Add a sharing metadata image for displaying links nicely

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#56]
**Is this issue a feature request or a bug report?**

- [x] Feature
- [ ] Bug

**What is the expected behaviour/what feature are you proposing?**

I posted the link on twitter and there's no nice thumbnail. Would be great to have something, maybe the favicon icon?

![Screenshot from 2019-10-01 22-06-28](https://user-images.githubusercontent.com/14791708/66000784-15001680-e498-11e9-8b08-1bdc429f957a.png)

**Comment by jamietanna** [comment]
I've found that https://cards-dev.twitter.com/validator can be quite useful for validating that the markup is well-formed.

**Comment by HERBOD7** [comment]
@AnnaDodson  I can do it.

**Comment by AnnaDodson** [comment]
Thanks @HERBOD7

**Comment by HERBOD7** [comment]
@AnnaDodson what's your opinion about adding another tag for twitter card, title and ..?

**Comment by AnnaDodson** [comment]
Do you mean having a different thumbnail image for different posts or pages on the site? Do you have an example?

**Comment by HERBOD7** [comment]
@AnnaDodson I mean that add title, description and etc in meta that when sharing a post in Twitter, 
it has post title, description and etc. like:
![Screenshot from 2019-11-04 11-10-57](https://user-images.githubusercontent.com/26714715/68105500-f0aeb400-fef3-11e9-8310-7e50c95037fa.png)
