### ISSUE TITLE
Remove accidentally committed `.DS_Store`

### ISSUE THREAD

**Issue by jamietanna** [AnnaDodson/hacktoberfest-website#59]
**Is this issue a feature request or a bug report?**

- [ ] Feature
- [x] Bug

**What is the expected behaviour/what feature are you proposing?**

`.DS_Store` should not exist in the repo. It is a temporary file used on MacOS, but not necessary for the operation of non-Mac clients, and should generally not be tracked in source control.

**What is the actual behaviour?**

`.DS_Store` is in the repo

**Remediation Steps**

1. `git rm .DS_Store`
1. Add `.DS_Store` to the `.gitignore`

**Comment by HERBOD7** [comment]
@AnnaDodson and @jamietanna I can do it.
