### ISSUE TITLE
On the events page - add a JavaScript check so if the date has passed the `event--done` class is added to it

### ISSUE THREAD

**Issue by AnnaDodson** [AnnaDodson/hacktoberfest-website#63]
**Is this issue a feature request or a bug report?**

- [x] Feature
- [ ] Bug

**What is the expected behaviour/what feature are you proposing?**

On the events listings, it would be great to automate the strike through on events that have passed.

Add JavaScript check to see if the date of the event is in the past and add the strike through class to the event listing if it is. Might want to consider using a date library such as [momentjs](https://momentjs.com/).

Note the page still needs to render if the user doesn't have JavaScript enabled

**Comment by jrp90** [comment]
I'll claim this one if that's cool! 👍

**Comment by AnnaDodson** [comment]
Go for it!

**Comment by AnnaDodson** [comment]
Great, thanks!
