### ISSUE TITLE
On the events page - fix the incorrect date on 'Homebrew Website Club (1/3)'  from 16th to 2nd 

### ISSUE THREAD

**Issue by RizBizKits** [AnnaDodson/hacktoberfest-website#64]
**Is this issue a feature request or a bug report?**

- [ ] Feature
- [x] Bug

**What is the expected behaviour/what feature are you proposing?**

The 1st Homebrew Website Club in October was held on the 2nd and that's what the date should be changed to.

**What is the actual behaviour?**

<img width="608" alt="Screen Shot 2019-10-05 at 8 04 06 PM" src="https://user-images.githubusercontent.com/27157262/66259713-39b40100-e7ac-11e9-9b74-00c9a9d3b059.png">

**How can the bug be reproduced?**

**Comment by jamesallured** [comment]
I'll take this one! ✌🏼
